export const EVENT_ID_DESCRIPTIONS: Record<number, string> = {
  // Account logon
  4624: 'An account was successfully logged on',
  4625: 'An account failed to log on',
  4634: 'An account was logged off',
  4647: 'User initiated logoff',
  4648: 'A logon was attempted using explicit credentials',
  4672: 'Special privileges assigned to new logon',
  4673: 'A privileged service was called',
  4674: 'An operation was attempted on a privileged object',
  // Account management
  4720: 'A user account was created',
  4722: 'A user account was enabled',
  4723: 'An attempt was made to change an account password',
  4724: 'An attempt was made to reset an account password',
  4725: 'A user account was disabled',
  4726: 'A user account was deleted',
  4727: 'A security-enabled global group was created',
  4728: 'A member was added to a security-enabled global group',
  4729: 'A member was removed from a security-enabled global group',
  4730: 'A security-enabled global group was deleted',
  4731: 'A security-enabled local group was created',
  4732: 'A member was added to a security-enabled local group',
  4733: 'A member was removed from a security-enabled local group',
  4756: 'A member was added to a security-enabled universal group',
  4757: 'A member was removed from a security-enabled universal group',
  4764: 'A group type was changed',
  4767: 'A user account was unlocked',
  4768: 'A Kerberos authentication ticket (TGT) was requested',
  4769: 'A Kerberos service ticket was requested',
  4771: 'Kerberos pre-authentication failed',
  4776: 'The domain controller attempted to validate credentials for an account',
  4778: 'A session was reconnected to a window station',
  4779: 'A session was disconnected from a window station',
  // Process
  4688: 'A new process has been created',
  4689: 'A process has exited',
  4697: 'A service was installed in the system',
  4698: 'A scheduled task was created',
  4699: 'A scheduled task was deleted',
  4700: 'A scheduled task was enabled',
  4701: 'A scheduled task was disabled',
  4702: 'A scheduled task was updated',
  // Object access
  4656: 'A handle to an object was requested',
  4657: 'A registry value was modified',
  4660: 'An object was deleted',
  4663: 'An attempt was made to access an object',
  4670: 'Permissions on an object were changed',
  // Network
  5140: 'A network share object was accessed',
  5142: 'A network share object was added',
  5144: 'A network share object was deleted',
  5145: 'A network share object was checked to see whether client can be granted desired access',
  5156: 'The Windows Filtering Platform has permitted a connection',
  5157: 'The Windows Filtering Platform has blocked a connection',
  5158: 'The Windows Filtering Platform has permitted a bind to a local port',
  // Policy
  4713: 'Kerberos policy was changed',
  4714: 'Encrypted data recovery policy was changed',
  4715: 'The audit policy on an object was changed',
  4716: 'Trusted domain information was modified',
  4717: 'System security access was granted to an account',
  4718: 'System security access was removed from an account',
  4739: 'Domain Policy was changed',
  4740: 'A user account was locked out',
  4741: 'A computer account was created',
  4742: 'A computer account was changed',
  4743: 'A computer account was deleted',
  // Audit
  1100: 'The event logging service has shut down',
  1102: 'The audit log was cleared',
  1104: 'The security log is now full',
  // Sysmon
  1: 'Process creation (Sysmon)',
  2: 'A process changed a file creation time (Sysmon)',
  3: 'Network connection (Sysmon)',
  4: 'Sysmon service state changed',
  5: 'Process terminated (Sysmon)',
  6: 'Driver loaded (Sysmon)',
  7: 'Image loaded (Sysmon)',
  8: 'CreateRemoteThread (Sysmon)',
  9: 'RawAccessRead (Sysmon)',
  10: 'ProcessAccess (Sysmon)',
  11: 'FileCreate (Sysmon)',
  12: 'RegistryEvent — Object create and delete (Sysmon)',
  13: 'RegistryEvent — Value Set (Sysmon)',
  14: 'RegistryEvent — Key and Value Rename (Sysmon)',
  15: 'FileCreateStreamHash (Sysmon)',
  17: 'PipeEvent — Pipe Created (Sysmon)',
  18: 'PipeEvent — Pipe Connected (Sysmon)',
  19: 'WmiEvent — WmiEventFilter activity (Sysmon)',
  20: 'WmiEvent — WmiEventConsumer activity (Sysmon)',
  21: 'WmiEvent — WmiEventConsumerToFilter activity (Sysmon)',
  22: 'DNS query (Sysmon)',
  23: 'FileDelete — File Delete archived (Sysmon)',
  25: 'ProcessTampering (Sysmon)',
  26: 'FileDeleteDetected (Sysmon)',
};

export function getEventIdDescription(eventId: number): string | null {
  return EVENT_ID_DESCRIPTIONS[eventId] ?? null;
}
